// src/lib/constants.ts

export const MVP_CONSTANTS = {
  // ETA
  PREP_TIME_BASE: 20,
  PREP_TIME_PER_ITEM: 2,
  QUEUE_THRESHOLD: 3,
  QUEUE_FACTOR_PER_ORDER: 3,
  TRAVEL_TIME_PER_KM: 4,
  BUFFER_MINUTES: 8,
  SCHEDULED_WINDOW: 10,

  // Slots
  SLOT_INTERVAL_MINUTES: 10,
  SCHEDULE_LEAD_TIME_MIN: 30,
  MAX_SCHEDULE_DAYS: 2,
  PREP_WINDOW_MIN: 45,

  // Auth
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  SESSION_MAX_AGE_DAYS: 7,
  BCRYPT_COST_FACTOR: 10,
  RESET_PASSWORD_EXPIRY_HOURS: 1,

  // Rate limiting
  AUTH_RATE_LIMIT_PER_MINUTE: 10,

  // Geocoding
  AUTOCOMPLETE_DEBOUNCE_MS: 300,

  // Polling
  POLLING_ACTIVE_MS: 10000,    // 10s for PREPARING/READY/OUT_FOR_DELIVERY
  POLLING_INACTIVE_MS: 30000,  // 30s for other active states

  // GDPR retention
  ORDER_RETENTION_YEARS: 5,
  ACCOUNT_DELETION_DAYS: 30,
  AUDIT_LOG_RETENTION_YEARS: 2,

  // Haversine
  EARTH_RADIUS_KM: 6371,
} as const;
